name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub 
      # run: docker login --username ${{ secrets.prod.DOCKERHUB_PASSWORD }} --password-server
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      env:
          DOCKERHUB_USERNAME: ${{ secrets.prod.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.prod.DOCKERHUB_PASSWORD }}
    - name: Build Docker image
      run: docker build -t shikha25/trade-image .

    - name: Push Docker image
      run: docker push shikha25/trade-image
      env:
          DOCKERHUB_USERNAME: ${{ secrets.prod.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.prod.DOCKERHUB_PASSWORD }}
