name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub 
      run: docker login --username ${{ secrets.prod.DOCKERHUB_PASSWORD }} --password-server

    - name: Build Docker image
      run: docker build -t shikha25/TradeImage .

    - name: Push Docker image
      run: docker push shikha25/TradeServiceImage
      env:
          DOCKERHUB_USERNAME: ${{ secrets.prod.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.prod.DOCKERHUB_PASSWORD }}
